// Preload: exposes only the safe vault API to the renderer.
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('vault', {
  ping: () => ipcRenderer.invoke('vault:ping'),
  status: () => ipcRenderer.invoke('vault:status'),
  defaultDir: () => ipcRenderer.invoke('vault:default-dir'),
  exists: (vaultDir) => ipcRenderer.invoke('vault:exists', { vaultDir }),
  selectDir: () => ipcRenderer.invoke('vault:select-dir'),
  reveal: (vaultDir) => ipcRenderer.invoke('vault:reveal', { vaultDir }),
  init: (vaultDir, password) => ipcRenderer.invoke('vault:init', { vaultDir, password }),
  unlock: (vaultDir, password) => ipcRenderer.invoke('vault:unlock', { vaultDir, password }),
  list: () => ipcRenderer.invoke('vault:list'),
  importFile: () => ipcRenderer.invoke('vault:import'),
  importFolder: () => ipcRenderer.invoke('vault:import-folder'),
  confirmImportFolder: () => ipcRenderer.invoke('vault:import-folder-confirm'),
  cancelImport: () => ipcRenderer.invoke('vault:cancel-import'),
  exportFolder: (prefix) => ipcRenderer.invoke('vault:export-folder', { prefix }),
  deleteFolder: (prefix) => ipcRenderer.invoke('vault:delete-folder', { prefix }),
  open: (fileId) => ipcRenderer.invoke('vault:open', { fileId }),
  read: (fileId) => ipcRenderer.invoke('vault:read', { fileId }),
  stream: (fileId) => ipcRenderer.invoke('vault:stream', { fileId }),
  streamClose: (token) => ipcRenderer.invoke('vault:stream-close', { token }),
  lanStart: (vaultDir, port) => ipcRenderer.invoke('vault:lan-start', { vaultDir, port }),
  lanStop: () => ipcRenderer.invoke('vault:lan-stop'),
  lanStatus: () => ipcRenderer.invoke('vault:lan-status'),
  lanIps: () => ipcRenderer.invoke('vault:lan-ips'),
  reencrypt: (fileId) => ipcRenderer.invoke('vault:reencrypt', { fileId }),
  closeFile: (fileId) => ipcRenderer.invoke('vault:close', { fileId }),
  remove: (fileId) => ipcRenderer.invoke('vault:delete', { fileId }),
  rename: (fileId, name) => ipcRenderer.invoke('vault:rename', { fileId, name }),
  exportFile: (fileId, suggestedName) => ipcRenderer.invoke('vault:export', { fileId, suggestedName }),
  changePassword: (newPassword) => ipcRenderer.invoke('vault:change-password', { newPassword }),
  lock: () => ipcRenderer.invoke('vault:lock'),
  onEvent: (cb) => ipcRenderer.on('vault:event', (_e, data) => cb(data)),
});
